// Generated by Lasy AI - https://lasy.ai
import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";
import { MetaPixelProvider } from "@/components/MetaPixelProvider";
import { ErrorBoundary } from "@/components/ErrorBoundary";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Lum IA - Seu Conselheiro Inteligente",
  description: "Apoio emocional, clareza mental e orientação prática 24 horas por dia",
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "Lum IA",
  },
  formatDetection: {
    telephone: false,
  },
  openGraph: {
    type: "website",
    siteName: "Lum IA",
    title: "Lum IA - Seu Conselheiro Inteligente",
    description: "Apoio emocional, clareza mental e orientação prática 24 horas por dia",
  },
  twitter: {
    card: "summary",
    title: "Lum IA - Seu Conselheiro Inteligente",
    description: "Apoio emocional, clareza mental e orientação prática 24 horas por dia",
  },
};

export const viewport: Viewport = {
  themeColor: "#9333ea",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="dark" suppressHydrationWarning>
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
        <link rel="icon" href="/icon.svg" type="image/svg+xml" />
        <link rel="apple-touch-icon" href="/icon-192.png" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="Lum IA" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="application-name" content="Lum IA" />
        
        {/* Meta Pixel noscript fallback */}
        <noscript>
          <img 
            height="1" 
            width="1" 
            style={{ display: 'none' }}
            src="https://www.facebook.com/tr?id=1392950065611433&ev=PageView&noscript=1"
            alt=""
          />
        </noscript>
        
        {/* Cache Manager & Service Worker Registration */}
        <Script id="cache-manager" strategy="afterInteractive">
          {`
            // Inicializar gerenciador de cache
            (async function() {
              try {
                // Importar e inicializar cache manager
                const { initializeCacheManager, setupStorageErrorHandling } = await import('@/lib/cache-manager');
                await initializeCacheManager();
                setupStorageErrorHandling();
                console.log('[App] Cache manager inicializado');
              } catch (error) {
                console.error('[App] Erro ao inicializar cache manager:', error);
              }

              // Registrar Service Worker
              if ('serviceWorker' in navigator) {
                try {
                  const registration = await navigator.serviceWorker.register('/sw.js');
                  console.log('[App] Service Worker registrado:', registration.scope);

                  // Atualizar SW quando houver nova versão
                  registration.addEventListener('updatefound', () => {
                    const newWorker = registration.installing;
                    if (newWorker) {
                      newWorker.addEventListener('statechange', () => {
                        if (newWorker.state === 'activated' && navigator.serviceWorker.controller) {
                          console.log('[App] Nova versão do SW ativada. Recarregando...');
                          window.location.reload();
                        }
                      });
                    }
                  });
                } catch (error) {
                  console.error('[App] Falha ao registrar Service Worker:', error);
                }
              }
            })();
          `}
        </Script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        <ErrorBoundary>
          <MetaPixelProvider>
            {children}
          </MetaPixelProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
